TRAIN:
  WEIGHT_DECAY: 0.3
  BASE_LR: 2e-4
  OPTIMIZER:
    BETAS: (0.9, 0.98)
  EPOCHS: 50
  WARMUP_EPOCHS: 10
DATA:
  IMG_SIZE: 224
MODEL:
  TYPE: vit
  NAME: vit_large_32
  VIT:
    PATCH_SIZE: 32
    WIDTH: 1024
    LAYERS: 24
    NUM_HEADS: 16
